default:
  image: node

stages:
  - build
  - test
  - deploy

build_job:
  stage: build
  before_script:
    # - git config --global gitlab.accesstoken 96FeGszBgXSCgeMzFspr
    # - git config --global credential.helper store
    # - echo "https://gitlab-ci-token:${CI_JOB_TOKEN}@${CI_SERVER_HOST}" >> ~/.git-credentials
    # - chmod 600 ~/.git-credentials
    # - chmod 644 ./ #~/builds/mxv-ex/mxs/mxs-log

  script:
    - echo "Hello, $GITLAB_USER_LOGIN!"
    - npm install -g typescript

    - cd ../
    # - ls
    - rm ./mxs_common -rf
    - git clone --branch dev https://gitlab-ci-token:${MXS_CI_JOB_TOKEN}@git.mxv.com.vn/mxv-ex/mxs/common.git mxs_common
    - cd mxs_common/
    # - ls -l
    - npm install
    - npm run build
    - cd build/
    - npm link
    - cd ../../mxs-log/

    - cd ../
    # - ls
    - rm ./mxs_share -rf
    - git clone --branch dev https://gitlab-ci-token:${MXS_CI_JOB_TOKEN}@git.mxv.com.vn/mxv-ex/mxs/mxs-share.git mxs_share
    - cd mxs_share/
    # - ls -l
    - npm install
    - npm link @mxs/common
    - npm run build
    - cd build/
    - npm link
    - cd ../../mxs-log/

    - npm install --legacy-peer-deps
    - npm link @mxs/common @mxs/share # tìm cách cài đặt 2 modules [@mxs/common @mxs/share] thì mới build được
    - CI=false npm run build
    - cp -f ./package.json ./build/
    - echo "build done."

  artifacts:
    paths:
      - build/
    expire_in: 1 hour

test_job:
  stage: test
  needs: [build_job]
  script:
    - echo "This job tests something. It will only run when all jobs in the"
    - echo "build stage are complete."
# test_job1:
#   stage: test
#   script:
#     - echo "This job tests something"
# test_job2:
#   stage: test
#   script:
#     - echo "This job tests something, but takes more time than test-job1."
#     - echo "After the echo commands complete, it runs the sleep command for 20 seconds"
#     - echo "which simulates a test that runs 20 seconds longer than test-job1"
#     - sleep 20

deploy_dev:
  stage: deploy
  image: node:alpine
  variables:
    GIT_STRATEGY: none
  # only:
  #   - main
  #   - master
  before_script:
    - apk update && apk add openssh-client bash # Install: ssh-agent bash
    - eval $(ssh-agent -s) # chạy ssh-agent tương ứng với Gitlab Runner hiện tại
    - bash -c 'ssh-add <(echo "$SSH_MXVDEV_PRIVATE_KEY")' # thêm nội dung của biến SSH_PRIVATE_KEY vào agent store
    - mkdir -p ~/.ssh # tạo folder ~/.ssh
    - ssh-keyscan -H $SSH_MXVDEV_SERVER_IP >> ~/.ssh/known_hosts # Scan lấy SSH Host key cho địa chỉ IP server, Được kết quả bao nhiêu thì thêm vào file known_hosts
    - chmod 644 ~/.ssh/known_hosts # Sửa lại quyền của file known_hosts

  script:
    # Thực hiện SSH vào server, chuyển tới folder project
    # - ssh $SSH_USER@$SSH_SERVER_IP
    - scp -r build/. $SSH_MXVDEV_USER@$SSH_MXVDEV_SERVER_IP:/var/mxs/mxs-log/
  dependencies:
    - build_job

  when: manual

deploy_staging:
  stage: deploy
  image: node:alpine
  variables:
    GIT_STRATEGY: none
  # only:
  #   - main
  #   - master
  before_script:
    - apk update && apk add openssh-client bash # Install: ssh-agent bash
    - eval $(ssh-agent -s) # chạy ssh-agent tương ứng với Gitlab Runner hiện tại
    - bash -c 'ssh-add <(echo "$SSH_PRIVATE_KEY")' # thêm nội dung của biến SSH_PRIVATE_KEY vào agent store
    - mkdir -p ~/.ssh # tạo folder ~/.ssh
    - ssh-keyscan -H $SSH_SERVER_IP >> ~/.ssh/known_hosts # Scan lấy SSH Host key cho địa chỉ IP server, Được kết quả bao nhiêu thì thêm vào file known_hosts
    - chmod 644 ~/.ssh/known_hosts # Sửa lại quyền của file known_hosts

  script:
    # Thực hiện SSH vào server, chuyển tới folder project
    # - ssh $SSH_USER@$SSH_SERVER_IP
    - scp -r build/. $SSH_USER@$SSH_SERVER_IP:/var/mxs/mxs-log/
  dependencies:
    - build_job
    
  when: manual
